# gamelist
game_list = [" mine craft" , "counter strike" , "devil may cry" , "resident evil" , "hitman 2" , "call of duty" , "battle field" , "fortnite" ] 
print (game_list [+1])
print (game_list [+2])
print (game_list [+3])
print (game_list [-1])
print (game_list [-2])
print (game_list [-3])
print (len(game_list))
game_list.append("Pubg")
print (game_list)
game_list.remove ("fortnite")
print (game_list)
game_list.remove("resident evil")
print (game_list)
game_list.extend("hitman 2")
print (game_list)
game_list.insert(3 , "call of duty")
print (game_list)
game_list.pop(2)
print (game_list)
# name list (boy)
boy_names = [ "Mani" , "mohammad" , "ali" , "amir hossein" , "hossein" , "abolfazl" , "amir abbas" , "samiyar" , "mohammad taha" , "mohammad reza" , "mohammad mehdi"]
print (boy_names [+1])
print (boy_names [+2])
print (boy_names [+3])
print (boy_names [-1])
print (boy_names [-2])
print (boy_names [-3])
print (len(boy_names))
boy_names.append ("alireza")
print (boy_names)
boy_names.remove ("alireza")
print (boy_names)
boy_names.extend("Mani")
print (game_list)
boy_names.insert(3 , "saleh")
print (boy_names)
boy_names.pop(2)
print(boy_names)
# Girl name
girls_name = [ "Nika" , "fateme" , "zahra" , "zeinab" , "maryam" , "mobina" , "setayesh" , "reyhane"]
print (len(girls_name))
print (girls_name [2])
print (girls_name [3])
print (girls_name [0])
print (girls_name [-2])
print (girls_name [-3])
print (girls_name [-5])
print(len(girls_name))
girls_name.append (" roghaye")
print (girls_name)
girls_name.remove("setayesh")
print(girls_name)
girls_name.extend ("Nika")
print (girls_name)
girls_name.insert (2 , "nazanin")
print (girls_name)
girls_name.pop (5)
print(girls_name)
#Team
team = [ "man city" , "real madrid" , "bayern" , "inter" , "liverpool" , "arsenal" , "atlectico"]
print (team[1])
print (team[2])
print (team[0])
print (team[-1])
print (team[-2])
print (team[-3])
print (len(team))
team.append ("leipzig")
print (team)
team.remove ("arsenal")
print (team)
team.extend ("real madrid")
print (team)
team.insert (2 , "munich")
print (team)
team.pop ( 5 )
print (team)
#family
family = [ "Yousefi" , "Jadidi" ,  "mohammadi" , "hosseini" , "ahmadi" , "rezaii" , "karimi" , "mousavi" , "jafari" , "sadeghi"]
print (len(family))
print(family [1])
print (family [2])
print(family [3])
print(family [-1])
print(family [-5])
print(family [-6])
family.append ("kazemi")
print (family)
family.remove ("mohammadi")
print (family)
family.extend ("Yousefi")
print(family)
family.insert (2 , "hashhemi")
print (family)
family.pop (4)
print (family)